# Generated by Django 5.2.8 on 2025-12-28 22:22

import django.db.models.deletion
import django.utils.timezone
import liveExam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0021_alter_exam_random_question_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        db_index=True,
                        default=liveExam.models.generate_pin,
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby"),
                            ("question", "Question"),
                            ("reveal", "Reveal"),
                            ("finished", "Finished"),
                        ],
                        default="lobby",
                        max_length=12,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("current_index", models.PositiveIntegerField(default=0)),
                ("question_started_at", models.DateTimeField(blank=True, null=True)),
                ("question_ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="blog.exam",
                    ),
                ),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=32)),
                ("avatar_key", models.CharField(default="avatar_1", max_length=32)),
                ("client_id", models.CharField(db_index=True, max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("is_connected", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="liveExam.livesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "client_id")},
            },
        ),
        migrations.CreateModel(
            name="LiveAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.IntegerField()),
                ("choice_id", models.IntegerField()),
                ("is_correct", models.BooleanField(default=False)),
                ("answer_ms", models.IntegerField(default=0)),
                ("awarded_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="liveExam.liveplayer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="liveExam.livesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "player", "question_id")},
            },
        ),
    ]
