# Generated by Django 5.2.8 on 2025-12-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveExam", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="liveplayer",
            constraint=models.UniqueConstraint(
                fields=("session", "client_id"), name="uniq_player_per_session_client"
            ),
        ),
    ]
