# Generated by Django 5.2.8 on 2025-12-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveExam", "0002_liveplayer_uniq_player_per_session_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="current_question_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="livesession",
            name="question_seconds",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
