# Generated by Django 5.1.3 on 2025-11-26 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_subscriber"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Sual")),
                (
                    "answer_text",
                    models.TextField(blank=True, null=True, verbose_name="Cavab"),
                ),
                (
                    "visible_to_all",
                    models.BooleanField(default=False, verbose_name="Hamı görə bilər"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif",
                    ),
                ),
                (
                    "visible_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions_can_see",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Görə bilən istifadəçilər",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual",
                "verbose_name_plural": "Suallar",
                "ordering": ["-created_at"],
            },
        ),
    ]
