# Generated by Django 5.1.3 on 2025-11-26 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_question"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Blok adı")),
                ("description", models.TextField(blank=True, verbose_name="Qısa izah")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("test", "Test imtahanı"),
                            ("written", "Yazılı / praktiki"),
                        ],
                        default="test",
                        max_length=20,
                        verbose_name="İmtahan tipi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Əgər söndürsəniz, tələbələr bu imtahanı görə bilməyəcək.",
                        verbose_name="Aktivdir?",
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 30. Boş saxlasanız, ümumi vaxt limiti olmayacaq.",
                        null=True,
                        verbose_name="Ümumi imtahan müddəti (dəqiqə)",
                    ),
                ),
                (
                    "default_question_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 60. Boş saxlasanız, sual basisində vaxt limiti olmayacaq.",
                        null=True,
                        verbose_name="Hər sual üçün default vaxt (saniyə)",
                    ),
                ),
                (
                    "max_attempts_per_user",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Məs: 1, 2, 3... Boş saxlasanız, attempts limitsiz olacaq.",
                        null=True,
                        verbose_name="Bir istifadəçi üçün maksimum cəhd sayı",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif",
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan bloku",
                "verbose_name_plural": "İmtahan blokları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Eyni user üçün 1, 2, 3 və s.",
                        verbose_name="Cəhd nömrəsi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (yarımçıq saxlanılıb)"),
                            ("in_progress", "Davam edir"),
                            ("submitted", "Təslim edilib"),
                            ("expired", "Vaxt bitib"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Faktiki davametmə müddəti (saniyə)",
                    ),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="blog.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan cəhdi",
                "verbose_name_plural": "İmtahan cəhdləri",
                "ordering": ["-started_at"],
                "unique_together": {("user", "exam", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Sual mətni")),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True,
                        verbose_name="Düzgün cavab / ideal cavab (yazılı üçün)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "answer_mode",
                    models.CharField(
                        choices=[
                            ("single", "Tək düzgün cavab"),
                            ("multiple", "Birdən çox düzgün cavab"),
                        ],
                        default="single",
                        help_text="Yalnız test imtahanları üçün mənalıdır.",
                        max_length=20,
                        verbose_name="Cavab rejimi",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Boş saxlasanız, Exam.default_question_time_seconds istifadə olunacaq.",
                        null=True,
                        verbose_name="Bu sual üçün vaxt limiti (saniyə)",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="blog.exam",
                        verbose_name="İmtahan bloku",
                    ),
                ),
            ],
            options={
                "verbose_name": "İmtahan sualı",
                "verbose_name_plural": "İmtahan sualları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Variant mətni"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, verbose_name="Düzgün variantdır?"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="blog.examquestion",
                        verbose_name="Sual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual variantı",
                "verbose_name_plural": "Sual variantları",
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Yazılı cavab"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Düzgündür?"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="blog.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="blog.examquestion",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="selected_in_answers",
                        to="blog.examquestionoption",
                        verbose_name="Seçilmiş variantlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual cavabı",
                "verbose_name_plural": "Sual cavabları",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
