# Generated by Django 5.1.3 on 2025-11-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_exam_examattempt_examquestion_examquestionoption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
