# Generated by Django 5.2.8 on 2025-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_image_alter_post_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="checked_by_teacher",
            field=models.BooleanField(
                default=False, verbose_name="Müəllim tərəfindən yoxlanılıb?"
            ),
        ),
    ]
