# Generated by Django 5.2.8 on 2025-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_examattempt_checked_by_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="teacher_feedback",
            field=models.TextField(blank=True, verbose_name="Müəllimin rəyi"),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="teacher_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="0–100 arası bal.",
                null=True,
                verbose_name="Müəllimin verdiyi bal (%)",
            ),
        ),
    ]
