# Generated by Django 5.2.8 on 2025-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_examattempt_teacher_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="teacher_feedback",
            field=models.TextField(blank=True, verbose_name="Müəllim rəyi (sual üzrə)"),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="teacher_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Bu suala verilən bal. (məs: 0–10 və ya 0–20 və s.)",
                null=True,
                verbose_name="Müəllim balı (sual üzrə)",
            ),
        ),
    ]
