# Generated by Django 5.2.8 on 2025-12-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_examanswer_teacher_feedback_examanswer_teacher_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="exam_uploads/"),
        ),
    ]
