# Generated by Django 5.2.8 on 2025-12-12 21:57

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_examanswer_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="exam_uploads/",
                validators=[
                    blog.validators.validate_file_extension,
                    blog.validators.validate_file_size,
                    blog.validators.validate_zip_contents,
                ],
            ),
        ),
    ]
