# Generated by Django 5.2.8 on 2025-12-12 22:14

import blog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_examanswer_uploaded_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examanswer",
            name="uploaded_file",
        ),
        migrations.CreateModel(
            name="ExamAnswerFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="exam_uploads/",
                        validators=[
                            blog.validators.validate_file_extension,
                            blog.validators.validate_file_size,
                            blog.validators.validate_zip_contents,
                        ],
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklənmə tarixi"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="blog.examanswer",
                        verbose_name="Cavab",
                    ),
                ),
            ],
        ),
    ]
