# Generated by Django 5.2.8 on 2025-12-13 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_remove_examanswer_uploaded_file_examanswerfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="access_code",
            field=models.CharField(
                blank=True,
                help_text="İstəyə görə əlavə təhlükəsizlik üçün 6 rəqəmli kod.",
                max_length=6,
                verbose_name="İmtahan kodu (6 rəqəm)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Yalnız bu istifadəçilər imtahanı görə / başlaya bilsin (qrupdan əlavə olaraq).",
                related_name="allowed_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="İcazəli tələbələr (fərdi)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Aktivdirsə, imtahan tələbə siyahısı məhdudiyyəti olmadan görünə bilər.",
                verbose_name="Hamı üçün açıqdır?",
            ),
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Qrup adı / nömrəsi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="student_groups_as_student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələbələr",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tələbə qrupu",
                "verbose_name_plural": "Tələbə qrupları",
                "ordering": ["name"],
                "unique_together": {("teacher", "name")},
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bu qruplardakı bütün tələbələr imtahana giriş icazəsi alır.",
                related_name="exams",
                to="blog.studentgroup",
                verbose_name="İcazəli qruplar",
            ),
        ),
    ]
