# Generated by Django 5.2.8 on 2025-12-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_questionblock_time_limit_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="points",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="examquestionoption",
            name="label",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=1,
                null=True,
            ),
        ),
    ]
