# Generated by Django 5.2.8 on 2025-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_examquestion_fingerprint_examquestion_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="default_question_points",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
