# Generated by Django 5.2.8 on 2025-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_exam_default_question_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="random_question_count",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Əgər 0 olarsa, bütün suallar düşür. Əgər rəqəm yazılarsa (məs: 7), bloklardan qarışıq şəkildə cəmi o qədər sual seçilir.",
                verbose_name="Tələbəyə göstəriləcək sual sayı",
            ),
        ),
    ]
