# Generated by Django 5.2.8 on 2026-01-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_alter_examquestion_enable_paint"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="has_paint",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="paint_data_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="paint_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="exam_paints/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="paint_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
