# Generated by Django 5.2.8 on 2026-01-10 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_examanswer_has_paint_examanswer_paint_data_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam", "status"], name="blog_examat_user_id_f3b228_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam", "-started_at"],
                name="blog_examat_user_id_f2665a_idx",
            ),
        ),
    ]
